Repository wecode-bootcamp-korea/11-MagicConch-backend, pull requests merged in 2020-09, with the labels that each got.

#1 [11기 문태기] Add: 회원가입, 로그인 엔드포인트 작성 및 각각의 unittest 작성
  .vscode/settings.json
  kinfolk/settings.py
  kinfolk/urls.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20200903_0819.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/urls.py
  user/validator.py
  user/views.py
Labels: Status: 리뷰 요청

#4 [김태하 ]Feature/products
  .gitignore
  .vscode/settings.json
  kinfolk/settings.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/urls.py
  product/views.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20200903_0819.py
  user/models.py
Labels: Status: 리뷰 요청

#5 Add[11기 문태기]: Kakao 소셜 로그인 엔드포인트 및 UnitTest 작성완료
  basket/migrations/0003_auto_20200909_0539.py
  basket/migrations/0003_auto_20200909_2345.py
  basket/views.py
  product/migrations/0002_auto_20200909_0155.py
  product/migrations/0003_remove_shopproduct_category.py
  product/models.py
  user/migrations/0001_initial.py
  user/tests.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: Accepted

#7 [김태하]Feature/products
  .gitignore
  .vscode/settings.json
  basket/migrations/0001_initial.py
  basket/migrations/0002_remove_basket_quantity.py
  basket/migrations/0003_auto_20200909_0539.py
  basket/migrations/0003_auto_20200909_2345.py
  basket/urls.py
  kinfolk/settings.py
  kinfolk/urls.py
  product/migrations/0001_initial.py
  product/models.py
  product/tests.py
  product/urls.py
  product/views.py
  user/migrations/0001_initial.py
  user/tests.py
  user/urls.py
Labels: Status: 리뷰 요청

#8 [11기 문태기] Add:Feature/basket 장바구니 구현
  basket/migrations/0002_auto_20200910_1315.py
  basket/views.py
  product/migrations/0002_auto_20200909_0155.py
  product/migrations/0002_auto_20200910_1315.py
  product/migrations/0003_remove_shopproduct_category.py
  product/models.py
  user/urls.py
Labels: Status: Conflict 해결 요청, Status: 리뷰 요청
